### ISSUE TITLE
how to get the current selector in onJustify ?

### ISSUE THREAD

**Issue by jerryc127** [nk-o/flickr-justified-gallery#2]
### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
1.0.7

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

visit the website, it will show the big image first and show the justified images

![ddddd](https://user-images.githubusercontent.com/16351105/103154980-a9aa0f00-47d6-11eb-9b30-abb936bfb8eb.gif)

I want to set the .fj-gallery or img to opacity 0,
and then call the onJustify  to set opacity  to 1.

i try to use 'this' in onJustify , but it points to Window object
so how to get the current selector in onJustify ?

**Comment by nk-o** [comment]
Hey.  
  
This code working with no problems. `this` points to the class instance, where you can find helpful data.

```javascript
fjGallery( document.querySelectorAll('.fj-gallery'), {
    onInit: function() {
        console.log(this.$container);
    },
    onJustify: function() {
        console.log(this.$container);
    },
});
```

Just keep in mind, that it will work only when you manually init gallery.
